### ISSUE TITLE
Not support swagger tool

### ISSUE THREAD

**Issue by dingxiaobohrbeu** [chujianyun/Spring-MultiRequestBody#2]
Your tools is very good.  But using swagger to post request by using mutil  body parameter  will case errror.
This is the error code .  Because the swagger don't support mutil body parameter.
It will be better if it support  swagger .

`2019-03-12 16:50:56,693 [,] ERROR DirectJDKLog.java:182 - Servlet.service() for servlet [dispatcherServlet] in context with path [/ipdportal] threw exception [Request processing failed; nested exception is com.alibaba.fastjson.JSONException: syntax error, pos 1, json : data] with root cause
com.alibaba.fastjson.JSONException: syntax error, pos 1, json :data
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1394)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1301)
	at com.alibaba.fastjson.JSON.parse(JSON.java:148)
	at com.alibaba.fastjson.JSON.parse(JSON.java:139)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:212)
	at com.huawei.common.annotation.MultiRequestBodyArgumentResolver.resolveArgument(MultiRequestBodyArgumentResolver.java:64)`

**Comment by originseek** [comment]
问一下大侠，你的这个feign传多个实体怎么解决的，还有swagger的问题我们项目中也用到了swagger
